### ISSUE TITLE
Question about Formula

### ISSUE THREAD

**Issue by TimothyGillespie** [tybayn/phasmo-cheat-sheet#1]
Hi!

I was curious how you arrived at this formula. It seems as though it is an approximation for a formula of the shape `ax^2+bx+c`. Is there more to it?
https://github.com/tybayn/phasmo-cheat-sheet/blob/ab3799bcfe64b3d79d0e42e9fe6e8436453e0980/scripts/metronome.js#L17

**Comment by tybayn** [comment]
Truth be told, I did a lot of research on the bpm of each ghosts footsteps, but the given bpms that I found didn't seem to match what I was hearing in YouTube videos. 

So instead I used a metronome to match the bps of the footsteps from videos, plotted the points as speed (m/s) vs bpm, and found the line of best fit that provided the smallest r^2 value. 

The formula in metronome.js is that line of best fit that converts the m/s to bpm. If you know of the actual formula, I would be more than happy to change it, but this is the one I have found to be closest to what is heard in game.

**Comment by TimothyGillespie** [comment]
It seems we have some "noise" when the ghost turns around as it seems double step. But when walking in a straight line the formula `((115/1.7) * speed) * speed_modifier` seems to work well and would be consisten with the interpretation that `1 step = (1.7 / (115 / 60)) m`. But I am not entirely sure yet if it works.

Since you, as well, have found the 115 bpm without using it I suppose you found that it doesn't actually work well?

**Comment by tybayn** [comment]
That is actually what I tried first, but I found it starts to deviate the further from 1.7 m/s you go. The Twins speeds seem to be okay, but anything past that starts to not match what is actually heard.

For example, the revenant. It has a max speed of 3.0 m/s when in line of sight. Using the equation (115/1.7) * 3.0 gives us about 203 bpm, but if you go to an example video (I used Psychos "Become a footstep pro in 9 minutes" on YouTube) the revenant speed seems to be closer to 230 bpm, which is quite a difference. Would you agree?
