### ISSUE TITLE
mic commands not working

### ISSUE THREAD

**Issue by CenTube** [tybayn/phasmo-cheat-sheet#13]
title says it all, not a single voice command is working for me. I tried it on multiple devices so the device shouldn't be the problem.

**Comment by tybayn** [comment]
Hey! Thanks for reaching out. There are a lot of moving parts so I'm going to ask a bunch of questions, even if they seem redundant or simple.

1. Does the Voice Command area in the settings tab have a message stating that the browser is incompatible?
2. If no, When you hit enable, does a little microphone icon appear on the tab of the settings menu?
3. If yes, does the microphone icon turn blue while you are talking and then turn green or red after you are talking?
4. Does the microphone icon disappear after saying a command (this shouldn't happen)?
5. Are there any errors that appear in the console?

**Comment by CenTube** [comment]
> 1. Does the Voice Command area in the settings tab have a message stating that the browser is incompatible? ✅
> 2. If no, When you hit enable, does a little microphone icon appear on the tab of the settings menu? ✅
> 3. If yes, does the microphone icon turn blue while you are talking and then turn green or red after you are talking? ❌
> 4. Does the microphone icon disappear after saying a command (this shouldn't happen)? ❌
> 5. Are there any errors that appear in the console? ❓(I don't know what console to check and how)
> 6. Did you grant your browser/page access to your microphone? ✅

Also, thanks for replying so quickly! I really appreciate the effort!

**Comment by CenTube** [comment]
Oh, and I had an idea for the desktop link, since I use the cheatsheet on my laptop and the desktop link on my PC. 
Is there any possibility for you to add checking evidence manually through hotkeys too?

Thanks!

**Comment by tybayn** [comment]
Oh yay! An error message makes this a little easier to debug. Can you expand that error and get all of it?

also, what OS and web browser are you using?

**Comment by CenTube** [comment]
SpeechRecognitionErrorEvent {isTrusted: true, error: 'network', message: '', type: 'error', target: SpeechRecognition, …}
isTrusted
: 
true
bubbles
: 
false
cancelBubble
: 
false
cancelable
: 
false
composed
: 
false
currentTarget
: 
SpeechRecognition {grammars: SpeechGrammarList, lang: 'en-US', continuous: false, interimResults: false, maxAlternatives: 1, …}
defaultPrevented
: 
false
error
: 
"network"
eventPhase
: 
0
message
: 
""
returnValue
: 
true
srcElement
: 
SpeechRecognition {grammars: SpeechGrammarList, lang: 'en-US', continuous: false, interimResults: false, maxAlternatives: 1, …}
target
: 
SpeechRecognition {grammars: SpeechGrammarList, lang: 'en-US', continuous: false, interimResults: false, maxAlternatives: 1, …}
timeStamp
: 
2312093
type
: 
"error"
[[Prototype]]
: 
SpeechRecognitionErrorEvent



I'm using Brave (chromium based)
(and yes, I tried turning off the shields and it still didn't work)

**Comment by tybayn** [comment]
I will look into it ( I didn't test brave browser in development), but it does look like it may be having an issue with the speech library https://github.com/brave/brave-browser/issues/2802 

I will let you know either way if i am able to get it working or not.

**Comment by tybayn** [comment]
As I am looking, it appears that only the 3 major browsers from the tech giant companies have the speech api support. Namely: Chrome, Edge, and Safari. Any other browser doesn't have this api access as they would have to pay Google in order to use them. 

I will add another catch condition to the code to state its not compatible with Brave, sorry for that

**Comment by CenTube** [comment]
Thank you so much!
