### ISSUE TITLE
Desktop Link Disconnects when Rebinding Keys

### ISSUE THREAD

**Issue by TonyGamer** [tybayn/phasmo-cheat-sheet#16]
When rebinding keys, the desktop link app disconnects from the server. If I reconnect afterwards, I see the "Listening..." text still, so it seems that that much is working. I would have made this issue specifically for the Desktop Link, but I couldn't find a repo for it anywhere

**Comment by tybayn** [comment]
Thanks for reaching out! Can I get a few more details from you?

What is your OS?
What browser are you using?
What keybinds are you attempting to change?
What are you changing them to?

**Comment by TonyGamer** [comment]
I tried to run it in a terminal and it just detaches the process immediately so I can't even see the logs

**Comment by tybayn** [comment]
Does the desktop link work with the default keybinds? I'm just trying to narrow down where the issue is originating since I'm unable to reproduce the error with Win 11 + Firefox

**Comment by TonyGamer** [comment]
The default keybinds work fine. In fact, trying it on my laptop earlier, I didn't have the issue, but I *do* have the issue on my Desktop computer. I'll try to record a short clip so you can see the exact behavior

**Comment by TonyGamer** [comment]
After booting back into my Windows environment, it doesn't seem to be happening anymore for some reason. I have no idea why it happened before, only that it did. The only weirdness I'm getting is that if I try to reconnect with the same linkid after disconnecting, it says the id isn't found

**Comment by tybayn** [comment]
We had one other person on my discord server submit a similar bug that it would randomly disconnect, and then it suddenly stopped disconnecting.

The link not working after disconnect is intentional. After disconnect on either end the room gets discarded to prevent any sort of security issue if a room is left open or unattended

**Comment by TonyGamer** [comment]
I see. Well, I'll close the issue for now. If it comes back up again, I'll go ahead and record it so you can see what it looks like
