### ISSUE TITLE
License

### ISSUE THREAD

**Issue by smaitlx1** [tybayn/phasmo-cheat-sheet#8]
Hey Ty,

I noticed there's no license attached to this code repo.  I see the MIT license listed on your others.  Can you attach a license to this one also so it's legally unambiguous what permissions you want to allow others who use this code?

**Comment by tybayn** [comment]
Hey! No worries. I will get that in place, let me move copyrighted phasmo assets (used with permission) out of this repo and onto my servers and triple check icons and sound files to make sure they are all open source. This way the entire repo can be licensed without issue.

Would a 'CC BY-NC-SA 4.0' license be permissive enough for your demonologist project?

**Comment by smaitlx1** [comment]
For the demonologist fork, that's fine.

I have another project I'd like to use the layout for that might be prohibited by commercial use. 
 While it won't be monetized/for sale, it will be for private use internally within a for-profit corporation, and the CC BY-NC-SA 4.0 defines "commercial use" as one "primarily intended for **commercial advantage** or monetary compensation" which could be a fuzzy spot.

Specifically, "commercial advantage" is pretty open to interpretation.

**Comment by smaitlx1** [comment]
Additionally, my uses would all be fine if your license completely excludes any Phasmophobia assets.

**Comment by tybayn** [comment]
I added a License and Readme, and I made sure all the files were good to go to the best of my knowledge, I think that should cover everything. If you could pull the changes into your fork or re-fork that would be appreciated. Any issues with those changes and additions?

**Comment by smaitlx1** [comment]
Hey Ty, sorry to reopen this, just wanted to let you know I encrypted the previous repository on my side in a 7z using a strong randomized password and the rest of the content that I will use going forward is easily viewable.  When you have a moment, please review my repo and confirm that this works for you.

**Comment by tybayn** [comment]
I just looked over the repo, everything looks good to me!
